name: Continuous Integration
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    name: Build and test on ${{ matrix.os }} ${{ matrix.architecture }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest, macos-latest, macos-13]
        include:
          - os: ubuntu-latest
            architecture: x64
          - os: ubuntu-24.04-arm
            architecture: arm64
          - os: windows-latest
            architecture: x64
          - os: macos-latest
            architecture: arm64
          - os: macos-13
            architecture: x64
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET SDK
      if: startsWith(matrix.os, 'ubuntu')
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          2.x
          8.x

    - name: Install .NET SDK
      if: matrix.os == 'macos-latest'
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.x

    - name: Install .NET SDK
      if: matrix.os == 'macos-13'
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 2.x

    - name: Install libssl
      if: matrix.os == 'ubuntu-latest'
      run: |
        wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2_amd64.deb
        sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2_amd64.deb

    - name: Install libssl
      if: matrix.os == 'ubuntu-24.04-arm'
      run: |
        wget http://ports.ubuntu.com/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.24_arm64.deb
        sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2.24_arm64.deb

    - name: Build and test
      run: dotnet test 
